routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/*
  Route::middleware(['web'])->group(function () {
  Route::namespace('Brackets\AdminAuth\Http\Controllers\Auth')->group(function () {
  Route::get('/login', 'LoginController@showLoginForm')->name('brackets/admin-auth::admin/login');
  Route::post('/login', 'LoginController@login');

  Route::any('/logout', 'LoginController@logout')->name('brackets/admin-auth::admin/logout');

  Route::get('/password-reset', 'ForgotPasswordController@showLinkRequestForm')->name('brackets/admin-auth::admin/password/showForgotForm');
  Route::post('/password-reset/send', 'ForgotPasswordController@sendResetLinkEmail');
  Route::get('/password-reset/{token}', 'ResetPasswordController@showResetForm')->name('brackets/admin-auth::admin/password/showResetForm');
  Route::post('/password-reset/reset', 'ResetPasswordController@reset');

  Route::get('/activation/{token}', 'ActivationController@activate')->name('brackets/admin-auth::admin/activation/activate');
  });
  });

  Route::middleware(['web', 'admin', 'auth:' . config('admin-auth.defaults.guard')])->group(function () {
  Route::namespace('Brackets\AdminAuth\Http\Controllers')->group(function () {
  Route::get('/', 'AdminHomepageController@index')->name('brackets/admin-auth::admin');
  });
  });
 */
/*
  Route::get('/', function () {
  return redirect(('/admin/login'));
  });
 */

/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/admin-users', 'Admin\AdminUsersController@index');
    Route::get('/admin/admin-users/create', 'Admin\AdminUsersController@create');
    Route::post('/admin/admin-users', 'Admin\AdminUsersController@store');
    Route::get('/admin/admin-users/{adminUser}/edit', 'Admin\AdminUsersController@edit')->name('admin/admin-users/edit');
    Route::post('/admin/admin-users/{adminUser}', 'Admin\AdminUsersController@update')->name('admin/admin-users/update');
    Route::delete('/admin/admin-users/{adminUser}', 'Admin\AdminUsersController@destroy')->name('admin/admin-users/destroy');
    Route::get('/admin/admin-users/{adminUser}/resend-activation', 'Admin\AdminUsersController@resendActivationEmail')->name('admin/admin-users/resendActivationEmail');
});

/* Auto-generated profile routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/profile', 'Admin\ProfileController@editProfile');
    Route::post('/admin/profile', 'Admin\ProfileController@updateProfile');
    Route::get('/admin/password', 'Admin\ProfileController@editPassword');
    Route::post('/admin/password', 'Admin\ProfileController@updatePassword');
});


/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/managers', 'Admin\UsersController@index');
    Route::get('/admin/managers/create', 'Admin\UsersController@create');
    Route::post('/admin/managers', 'Admin\UsersController@store');
    Route::get('/admin/managers/{user}/edit', 'Admin\UsersController@edit')->name('admin/users/edit');
    Route::post('/admin/managers/{user}', 'Admin\UsersController@update')->name('admin/users/update');
    Route::delete('/admin/managers/{user}', 'Admin\UsersController@destroy')->name('admin/users/destroy');
});

/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/manage_clients', 'Admin\ClientsController@index');
    Route::get('/admin/manage_clients/create', 'Admin\ClientsController@create');
    Route::post('/admin/manage_clients', 'Admin\ClientsController@store');
    Route::get('/admin/manage_clients/{client}/edit', 'Admin\ClientsController@edit')->name('admin/clients/edit');
    Route::post('/admin/manage_clients/{client}', 'Admin\ClientsController@update')->name('admin/clients/update');
    Route::delete('/admin/manage_clients/{client}', 'Admin\ClientsController@destroy')->name('admin/clients/destroy');
});

/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/user-levels', 'Admin\UserLevelsController@index');
    Route::get('/admin/user-levels/create', 'Admin\UserLevelsController@create');
    Route::post('/admin/user-levels', 'Admin\UserLevelsController@store');
    Route::get('/admin/user-levels/{userLevel}/edit', 'Admin\UserLevelsController@edit')->name('admin/user-levels/edit');
    Route::post('/admin/user-levels/{userLevel}', 'Admin\UserLevelsController@update')->name('admin/user-levels/update');
    Route::delete('/admin/user-levels/{userLevel}', 'Admin\UserLevelsController@destroy')->name('admin/user-levels/destroy');
});

/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/payment-methods', 'Admin\PaymentMethodsController@index');
    Route::get('/admin/payment-methods/create', 'Admin\PaymentMethodsController@create');
    Route::post('/admin/payment-methods', 'Admin\PaymentMethodsController@store');
    Route::get('/admin/payment-methods/{paymentMethod}/edit', 'Admin\PaymentMethodsController@edit')->name('admin/payment-methods/edit');
    Route::post('/admin/payment-methods/{paymentMethod}', 'Admin\PaymentMethodsController@update')->name('admin/payment-methods/update');
    //Route::delete('/admin/payment-methods/{paymentMethod}', 'Admin\PaymentMethodsController@destroy')->name('admin/payment-methods/destroy');
});

/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/rewards', 'Admin\RewardsController@index');
    Route::get('/admin/rewards/create', 'Admin\RewardsController@create');
    Route::post('/admin/rewards', 'Admin\RewardsController@store');
    Route::get('/admin/rewards/{reward}/edit', 'Admin\RewardsController@edit')->name('admin/rewards/edit');
    Route::post('/admin/rewards/{reward}', 'Admin\RewardsController@update')->name('admin/rewards/update');
    Route::delete('/admin/rewards/{reward}', 'Admin\RewardsController@destroy')->name('admin/rewards/destroy');
});

/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/penalties', 'Admin\PenaltiesController@index');
    Route::get('/admin/penalties/create', 'Admin\PenaltiesController@create');
    Route::post('/admin/penalties', 'Admin\PenaltiesController@store');
    Route::get('/admin/penalties/{penalty}/edit', 'Admin\PenaltiesController@edit')->name('admin/penalties/edit');
    Route::post('/admin/penalties/{penalty}', 'Admin\PenaltiesController@update')->name('admin/penalties/update');
    Route::delete('/admin/penalties/{penalty}', 'Admin\PenaltiesController@destroy')->name('admin/penalties/destroy');
});

/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/groups', 'Admin\GroupsController@index');
    Route::get('/admin/groups/create', 'Admin\GroupsController@create');
    Route::post('/admin/groups', 'Admin\GroupsController@store');
    Route::get('/admin/groups/{group}/edit', 'Admin\GroupsController@edit')->name('admin/groups/edit');
    Route::post('/admin/groups/{group}', 'Admin\GroupsController@update')->name('admin/groups/update');
    Route::delete('/admin/groups/{group}', 'Admin\GroupsController@destroy')->name('admin/groups/destroy');
});


/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/questions', 'Admin\QuestionsController@index');
    Route::get('/admin/questions/create', 'Admin\QuestionsController@create');
    Route::post('/admin/questions', 'Admin\QuestionsController@store');
    Route::get('/admin/questions/{question}/edit', 'Admin\QuestionsController@edit')->name('admin/questions/edit');
    Route::post('/admin/questions/{question}', 'Admin\QuestionsController@update')->name('admin/questions/update');
    Route::delete('/admin/questions/{question}', 'Admin\QuestionsController@destroy')->name('admin/questions/destroy');
});

/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/question-types', 'Admin\QuestionTypesController@index');
    Route::get('/admin/question-types/create', 'Admin\QuestionTypesController@create');
    Route::post('/admin/question-types', 'Admin\QuestionTypesController@store');
    Route::get('/admin/question-types/{questionType}/edit', 'Admin\QuestionTypesController@edit')->name('admin/question-types/edit');
    Route::post('/admin/question-types/{questionType}', 'Admin\QuestionTypesController@update')->name('admin/question-types/update');
    Route::delete('/admin/question-types/{questionType}', 'Admin\QuestionTypesController@destroy')->name('admin/question-types/destroy');
});

/* Auto-generated admin routes */
Route::middleware(['auth:' . config('admin-auth.defaults.guard'), 'admin'])->group(function () {
    Route::get('/admin/submitted-exams', 'Admin\QuestionsSubmissionsController@index');
    //Route::get('/admin/submitted-exams/create',           'Admin\QuestionsSubmissionsController@create');
    //Route::post('/admin/submitted-exams',                 'Admin\QuestionsSubmissionsController@store');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
#use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;

/**
 * Class User
 * @property int $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $first_name
 * @property string $second_name
 * @property string $third_name
 * @property string $last_name
 * @property string $mobile_number
 * @property \Carbon\Carbon $birthday
 * @property string $gender
 * @property int $country_id
 * @property int $user_type
 * @property int $user_status
 * @property int $client_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property string $deleted_at
 * @property \App\Models\Client $client
 * @property \App\Models\Country $country
 * @property \App\Models\Country $country_code
 * @property \Illuminate\Database\Eloquent\Collection $article_levels
 * @property \Illuminate\Database\Eloquent\Collection $articles
 * @property \Illuminate\Database\Eloquent\Collection $mobile_codes
 * @property \Illuminate\Database\Eloquent\Collection $questions_submissions
 * @property \Illuminate\Database\Eloquent\Collection $user_references
 * @property \Illuminate\Database\Eloquent\Collection $groups
 * @property \Illuminate\Database\Eloquent\Collection $users_notes
 * @property \Illuminate\Database\Eloquent\Collection $users_payment_infos
 * @property \Illuminate\Database\Eloquent\Collection $users_rejection_reasons
 *
 * @package App\Models
 */
class User extends Authenticatable #implements MustVerifyEmail
{

    use SoftDeletes,
        HasApiTokens,
        Notifiable;

    protected $casts = [
        'user_type' => 'int',
        'user_status' => 'int',
        'client_id' => 'int'
    ];
    protected $dates = [
        "created_at",
        "updated_at",
        "deleted_at",
    ];
    protected $hidden = [
        'password'
    ];
    protected $fillable = [
        'username',
        'email',
        'password',
        'first_name',
        'second_name',
        'third_name',
        'last_name',
        'mobile_number',
        'birthday',
        'gender',
        'country_id',
        'country_code_id',
        'user_type',
        'user_status',
        'client_id',
        'is_verified_email',
        'is_verified_mobile',
    ];
    protected $visible = [
        'id',
        'username',
        'email',
        'password',
        'first_name',
        'second_name',
        'third_name',
        'last_name',
        'user_type',
        'user_status',
        'client_id',
        'country_id',
        'country_code_id',
        'resource_url',
        'questions_submissions_url',
        'registration_request_url',
        'gender_name',
        'writers_url',
        'proofreaders_url',
        'client_name',
        'groups',
        'subgroups',
        'manpower_info',
        'country',
        'gender',
        'groupsIds',
        'mobile_number',
        'birthday'
    ];

//    protected $appends = ['resource_url', 'questions_submissions_url', 'registration_request_url', 'gender_name', 'writers_url', 'proofreaders_url'];

    /*     * *********************** ACCESSOR ************************* */

    // for Hased Password
    public function setPasswordAttribute($value)
    {
        return $this->attributes['password'] = Hash::needsRehash($value) ? Hash::make($value) : $value;
    }

    public function getResourceUrlAttribute()
    {
        return url('/admin/managers/' . $this->getKey());
    }

    public function getSystemProofreadersUrlAttribute()
    {
        return url('/admin/system/proofreaders/' . $this->getKey());
    }

    public function getQuestionsSubmissionsUrlAttribute()
    {
        return url('/admin/submitted-exams/' . $this->getKey());
    }

    public function getRegistrationRequestUrlAttribute()
    {
        return url('/admin/registration-request/' . $this->getKey());
    }

    public function getClientsWritersUrlAttribute()
    {
        return url('/admin/clients/writers/' . $this->getKey());
    }

    public function getQASRequestUrlAttribute()
    {
        return url('/admin/quality-assurance/' . $this->getKey());
    }

    public function getClientsProofreadersUrlAttribute()
    {
        return url('/admin/clients/proofreaders/' . $this->getKey());
    }

    public function getSystemWritersUrlAttribute()
    {
        return url('/admin/system/writers/' . $this->getKey());
    }

    public function client()
    {
        return $this->belongsTo(\App\Models\Client::class);
    }

    public function country()
    {
        return $this->belongsTo(\App\Models\Country::class);
    }

    public function country_code()
    {
        return $this->belongsTo(\App\Models\Country::class);
    }

    public function article_levels()
    {
        return $this->hasMany(\App\Models\ArticleLevel::class);
    }

    public function articles()
    {
        return $this->belongsToMany(\App\Models\Article::class, 'articles_blocked_users')
                        ->withPivot('id', 'deleted_at')
                        ->withTimestamps();
    }

    public function mobile_codes()
    {
        return $this->hasMany(\App\Models\MobileCode::class);
    }

    public function questions_submissions()
    {
        return $this->hasMany(\App\Models\QuestionsSubmission::class);
    }

    public function user_references()
    {
        return $this->hasMany(\App\Models\UserReference::class);
    }

    public function groups()
    {
        return $this->belongsToMany(\App\Models\Group::class, 'users_groups')
                        ->withPivot('id', 'deleted_at')
                        ->whereNull('users_groups.deleted_at')
                        ->withTimestamps();
    }

    public function subgroups()
    {
        return $this->belongsToMany(\App\Models\Subgroup::class, 'users_subgroups')
                        ->withPivot('id', 'deleted_at')
                        ->whereNull('users_subgroups.deleted_at')
                        ->withTimestamps();
    }

    public function users_notes()
    {
        return $this->hasMany(\App\Models\UsersNote::class);
    }

    public function users_payment_infos()
    {
        return $this->hasMany(\App\Models\UsersPaymentInfo::class);
    }

    public function users_rejection_reasons()
    {
        return $this->hasMany(\App\Models\UsersRejectionReason::class);
    }

    public function manpower_info()
    {
        return $this->hasOne(\App\Models\ManpowerInfo::class);
    }

    public function getGenderNameAttribute()
    {
        return \App\Constants\UserGender::getUserGenderNameByID($this->gender);
    }

    public function AauthAcessToken()
    {
        return $this->hasMany(OauthAccessToken::class);
    }

    public function userToken()
    {
        return $this->hasOne(\App\Models\UserToken::class);
    }

}

resources/views/admin/clients-proofreaders/create.blade.php
@extends('brackets/admin-ui::admin.layout.default')

@section('title', trans('admin.proofreader.actions.create'))

@section('body')

    <div class="container-xl">

        <div class="card">

            <clients-proofreaders-form
                :action="'{{ url('admin/proofreaders') }}'"
                
                inline-template>

                <form class="form-horizontal form-create" method="post" @submit.prevent="onSubmit" :action="this.action" novalidate>

                    <div class="card-header">
                        <i class="fa fa-plus"></i> {{ trans('admin.clients-proofreaders.actions.create') }}
                    </div>

                    <div class="card-body">

                        @include('admin.clients-proofreaders.components.form-elements')

                    </div>

                    <div class="card-footer">
	                    <button type="submit" class="btn btn-primary" :disabled="submiting">
		                    <i class="fa" :class="submiting ? 'fa-spinner' : 'fa-download'"></i>
		                    {{ trans('brackets/admin-ui::admin.btn.save') }}
	                    </button>
                    </div>

                </form>

            </clients-proofreaders-form>

        </div>

    </div>

@endsection

resources/views/admin/clients-proofreaders/edit.blade.php
@extends('brackets/admin-ui::admin.layout.default')

@section('title', trans('admin.proofreader.actions.edit', ['name' => $user->id]))

@section('body')

<div class="container-xl">

    <div class="card">
        <clients-proofreaders-form
            :action="'{{ $user->clients_proofreaders_url }}'"
            :data="{{ $user->toJson() }}"
            inline-template>

            <form class="form-horizontal form-edit" method="post" @submit.prevent="onSubmit" :action="this.action" novalidate>

                <div class="card-header">
                    <i class="fa fa-pencil"></i> {{ trans('admin.clients-proofreaders.actions.edit', ['name' => $user->first_name.' '.$user->last_name]) }}
                </div>

                <div class="card-body">

                    @include('admin.clients-proofreaders.components.form-elements')

                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary" :disabled="submiting">
                        <i class="fa" :class="submiting ? 'fa-spinner' : 'fa-download'"></i>
                        {{ trans('brackets/admin-ui::admin.btn.save') }}
                    </button>
                </div>

            </form>

        </clients-proofreaders-form>

    </div>

</div>

@endsection

resources/views/admin/clients-proofreaders/form.blade.php
@extends('brackets/admin-ui::admin.layout.default')

@section('title', trans('admin.proofreader.actions.edit', ['name' => $proofreader->id]))

@section('body')

    <div class="container-xl">

        <div class="card">

            <clients-proofreaders-form
            :action="'{{ route('admin/clients/proofreaders/update', ['proofreader' => $proofreader]) }}'"
            :data="{{ $proofreader->toJson() }}"
            inline-template>
            
                <form class="form-horizontal" method="post" @submit.prevent="onSubmit" :action="this.action">

                    <div class="card-header">
                        <i class="fa fa-plus"></i> {{ trans('admin.clients-proofreaders.actions.edit', ['name' => $proofreader->id]) }}
                    </div>

                    <div class="card-body">

                        
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">
                            <i class="fa" :class="submiting ? 'fa-spinner' : 'fa-download'"></i>
                            {{ trans('brackets/admin-ui::admin.btn.save') }}
                        </button>
                    </div>

                </form>

            </clients-proofreaders-form>

        </div>

    </div>

@endsection

resources/views/admin/clients-proofreaders/index.blade.php
@extends('brackets/admin-ui::admin.layout.default')

@section('title', trans('admin.clients-proofreaders.actions.index'))

@section('body')

<clients-proofreaders-listing
    :data="{{ $data->toJson() }}"
    :url="'{{ url('admin/clients/proofreaders') }}'"
    inline-template>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> {{ trans('admin.clients-proofreaders.actions.index') }}
                </div>
                <div class="card-body" v-cloak>
                    <form @submit.prevent="">
                        <div class="row">
                            <div class="col col-xl-3 form-group">
                                <div class="input-group">
                                    <input class="form-control" placeholder="{{ trans('brackets/admin-ui::admin.placeholder.search') }}" v-model="search" @keyup.enter="filter('search', $event.target.value)" />
                                    <span class="input-group-append">
                                        <button type="button" class="btn btn-primary" @click="filter('search', search)"><i class="fa fa-search"></i>&nbsp; {{ trans('brackets/admin-ui::admin.btn.search') }}</button>
                                    </span>
                                </div>
                            </div>
                            <div class="col col-xl-3 form-group">
                                <div class="input-group">
                                    <select v-model="client_id" class="form-control" id="client_id" name="client_id" @change="filter('client_id', client_id);">
                                        <option value="">{{ trans('admin.clients-proofreaders.select.option.all.label') }}</option>
                                        @foreach ($clients as $client)
                                        <option value="{{ $client['id'] }}">{{ $client['name'] }}</option>
                                        @endforeach 
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-auto ml-auto form-group ">
                                <select class="form-control" v-model="pagination.state.per_page">
                                    <option value="10">10</option>
                                    <option value="25">25</option>
                                    <option value="100">100</option>
                                </select>
                            </div>

                        </div>
                    </form>

                    <table class="table table-hover table-listing">
                        <thead>
                            <tr>
                                <th is='sortable' :column="'id'">{{ trans('admin.clients-proofreaders.columns.id') }}</th>
                                <th is='sortable' :column="'first_name'">{{ trans('admin.clients-proofreaders.columns.name') }}</th>
                                <th is='sortable' :column="'client_id'">{{ trans('admin.clients-proofreaders.columns.employer') }}</th>
                                <th is='sortable' :column="'username'">{{ trans('admin.clients-proofreaders.columns.username') }}</th>
                                <th is='sortable' :column="'is_active'">{{ trans('admin.clients-proofreaders.columns.is_active') }}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="(item, index) in collection">
                                <td>@{{ item.id }}</td>
                                <td>@{{ item.first_name +' '+ item.last_name }}</td>
                                <td>@{{ item.client.name }}</td>
                                <td>@{{ item.username }}</td>
                                <td>
                                    <label class="switch switch-3d switch-success">
                                        <input type="checkbox" class="switch-input" v-model="collection[index].user_status" @change="toggleSwitch(item.clients_proofreaders_url, 'user_status', collection[index])">
                                        <span class="switch-slider"></span>
                                    </label>
                                </td>
                                <td>
                                    <div class="row no-gutters">
                                        <div class="col-auto">
                                            <a class="btn btn-sm btn-spinner btn-info" :href="item.clients_proofreaders_url + '/edit'" title="{{ trans('brackets/admin-ui::admin.btn.edit') }}" role="button"><i class="fa fa-edit"></i></a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="row" v-if="pagination.state.total > 0">
                        <div class="col-sm">
                            <span class="pagination-caption">{{ trans('brackets/admin-ui::admin.pagination.overview') }}</span>
                        </div>
                        <div class="col-sm-auto">
                            <pagination></pagination>
                        </div>
                    </div>

                    <div class="no-items-found" v-if="!collection.length > 0">
                        <i class="icon-magnifier"></i>
                        <h3>{{ trans('brackets/admin-ui::admin.index.no_items') }}</h3>
                        <p>{{ trans('brackets/admin-ui::admin.index.try_changing_items') }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</clients-proofreaders-listing>

@endsection